openapi: 3.0.3
info:
  title: StepUp E-Shop API (MVP)
  version: "1.0.0"
  description: API specification for the StepUp MVP e-commerce system.

servers:
  - url: /api/v1

tags:
  - name: Products
  - name: Categories
  - name: Auth
  - name: Users
  - name: Cart
  - name: Wishlist
  - name: Orders
  - name: Admin

paths:

  ####################################################
  # PRODUCTS (Guest)
  ####################################################

  /products:
    get:
      tags: [Products]
      summary: Get all products
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

  /products/{id}:
    get:
      tags: [Products]
      summary: Get product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Product found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: Product not found

  /products/search:
    get:
      tags: [Products]
      summary: Search products
      parameters:
        - in: query
          name: query
          schema: { type: string }
      responses:
        "200":
          description: Search results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"

  /products/filter:
    get:
      tags: [Products]
      summary: Filter products
      parameters:
        - in: query
          name: category
          schema: { type: integer }
        - in: query
          name: minPrice
          schema: { type: number }
        - in: query
          name: maxPrice
          schema: { type: number }
        - in: query
          name: color
          schema: { type: string }
        - in: query
          name: size
          schema: { type: string }
        - in: query
          name: gender
          schema: { type: string }
      responses:
        "200":
          description: Filtered results
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "404":
          description: No products matching the filters found


  ####################################################
  # CATEGORIES
  ####################################################

  /categories:
    get:
      tags: [Categories]
      summary: Get categories
      responses:
        "200":
          description: Category list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"


  ####################################################
  # AUTH
  ####################################################

  /auth/register:
    post:
      tags: [Auth]
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        "201":
          description: User registered
        "400":
          description: Validation error

  /auth/login:
    post:
      tags: [Auth]
      summary: Login and get JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: JWT token returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        "401":
          description: Invalid credentials

  /auth/logout:
    post:
      tags: [Auth]
      summary: Log out (dummy for JWT)
      responses:
        "200":
          description: Logged out


  ####################################################
  # USERS
  ####################################################

  /users/me:
    get:
      tags: [Users]
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Profile returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserProfileResponse"

    put:
      tags: [Users]
      summary: Update profile
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserProfileUpdate"
      responses:
        "200":
          description: Profile updated

  ####################################################
  # Cart
  ####################################################
  /cart:
    get:
      tags: [Cart]
      summary: Get the users cart contents
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of <Cart Items>
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CartItem"
        "401":
          description: Not Authorised to view Cart
    post:
      tags: [Cart]
      summary: Add a new <Cart Item>
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CartAddRequest"
      responses:
        "200":
          description: <Cart Item> added successfully
        "400":
          description: Bad request format
  
  /cart/{cart_item_id}:
    # Update the carts' fields
    put:
      tags: [Cart]
      summary: Update Cart Item fields
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: cart_item_id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Cart Item Updated successfully



    delete:
      tags: [Cart]
      summary: Remove from cart
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: cart_item_id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Removed




  ####################################################
  # WISHLIST
  ####################################################

  /wishlist:
    get:
      tags: [Wishlist]
      summary: Get wishlist
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Wishlist items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/WishlistItem"

    post:
      tags: [Wishlist]
      summary: Add to wishlist
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WishlistAddRequest"
      responses:
        "201":
          description: Added to wishlist

  /wishlist/{product_id}:
    delete:
      tags: [Wishlist]
      summary: Remove from wishlist
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: product_id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Removed


  ####################################################
  # ORDERS
  ####################################################

  /orders:
    get:
      tags: [Orders]
      summary: Get user orders
      security:
        - bearerAuth: []
      responses:
        "200":
          description: List of user's orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"

    post:
      tags: [Orders]
      summary: Create an order
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrderRequest"
      responses:
        "201":
          description: Order created

  /orders/{id}:
    get:
      tags: [Orders]
      summary: Get order by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Order returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        "404":
          description: Not found

    put:
      tags: [Orders]
      summary: Edit order (ongoing only)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EditOrderRequest"
      responses:
        "200":
          description: Order updated

  /orders/{id}/cancel:
    put:
      tags: [Orders]
      summary: Cancel order
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Order cancelled


  ####################################################
  # ADMIN
  ####################################################

  /admin/products:
    post:
      tags: [Admin]
      summary: Create new product
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreate"
      responses:
        "201":
          description: Product created

  /admin/products/{id}:
    put:
      tags: [Admin]
      summary: Update product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductUpdate"
      responses:
        "200":
          description: Product updated

    delete:
      tags: [Admin]
      summary: Delete product
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Product deleted

  /admin/orders:
    get:
      tags: [Admin]
      summary: Get all orders
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Order list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"

  /admin/orders/{id}/status:
    put:
      tags: [Admin]
      summary: Update order status
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateOrderStatus"
      responses:
        "200":
          description: Status updated

  /admin/orders/{id}/reject:
    put:
      tags: [Admin]
      summary: Reject order
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: Order rejected


#########################################
# COMPONENTS (SCHEMAS & SECURITY)
#########################################

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    Product:
      type: object
      properties:
        product_id:   { type: integer }
        name:         { type: string }
        tags:         { type: string }
        image_url:    { type: string }
        # Show the minimal price of the product
        min_price:    { type: number }
        # Is the sum of all variants stock levels
        total_stock:  { type: integer }
        # The number of variants available
        no_variants:  { type: integer }
        cat_name:     { type: string }
        cat_id:       { type: integer }
        in_stock:     { type: boolean }

    ProductCreate:
      type: object
      required: [name, price, stock]
      properties:
        name:         { type: string }
        tags:         { type: string }
        image_url:    { type: string }
        # Show the minimal price of the product
        min_price:    { type: number }
        # Is the sum of all variants stock levels
        total_stock:  { type: integer }
        # The number of variants available
        no_variants:  { type: integer }
        cat_name:     { type: string }
        cat_id:       { type: integer }
        in_stock:     { type: boolean }

    ProductUpdate:
      type: object
      properties:
        name: { type: string }
        description: { type: string }
        image_url: { type: string }
        price: { type: number }
        stock: { type: integer }
        category_id: { type: integer }

    Category:
      type: object
      properties:
        category_id: { type: integer }
        name: { type: string }
        description: { type: string }

    RegisterRequest:
      type: object
      required: [username, email, password]
      properties:
        username: { type: string }
        email: { type: string }
        password: { type: string }

    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username: { type: string }
        password: { type: string }

    UserProfileResponse:
      type: object
      properties:
        user_id: { type: integer }
        username: { type: string }
        email: { type: string }
        profile:
          type: object
          properties:
            first_name: { type: string }
            last_name: { type: string }
            address: { type: string }
            city: { type: string }
            postal_code: { type: string }
            phone_number: { type: string }
            birthdate: { type: string, format: date }

    UserProfileUpdate:
      type: object
      properties:
        first_name: { type: string }
        last_name: { type: string }
        address: { type: string }
        city: { type: string }
        postal_code: { type: string }
        phone_number: { type: string }
        birthdate: { type: string, format: date }

    CartItem:
      type: object
      properties:
        cart_item_id: { type: integer }
        variant_id:   { type: integer }
        quantity:     { type: integer }
        productImage: { type: string  }

    CartAddRequest:
      type: object
      required: [variant_id, quantity]
      properties:
        variant_id: { type: integer }
        quantity:   { type: integer }


    WishlistItem:
      type: object
      properties:
        user_id: { type: integer }
        product_id: { type: integer }
        added_at: { type: string, format: date-time }

    WishlistAddRequest:
      type: object
      required: [product_id]
      properties:
        product_id: { type: integer }

    Order:
      type: object
      properties:
        order_id: { type: integer }
        user_id: { type: integer }
        order_date: { type: string, format: date-time }
        total_amount: { type: number }
        status: { type: string }
        shipping_address: { type: string }
        payment_method: { type: string }
        items:
          type: array
          items:
            $ref: "#/components/schemas/OrderItem"

    OrderItem:
      type: object
      properties:
        product_id: { type: integer }
        quantity: { type: integer }
        price_per_item: { type: number }

    CreateOrderRequest:
      type: object
      required: [items, shipping_address, payment_method]
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              product_id: { type: integer }
              quantity: { type: integer }
        shipping_address: { type: string }
        payment_method: { type: string }

    EditOrderRequest:
      type: object
      properties:
        shipping_address: { type: string }
        items:
          type: array
          items:
            type: object
            properties:
              product_id: { type: integer }
              quantity: { type: integer }

    UpdateOrderStatus:
      type: object
      properties:
        status: { type: string }